# automatically fetch contract sources from Etherscan
autofetch_sources: true

compiler:
    solc:
        optimizer:
            enabled: true
            runs: 1000000

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.1

reports:
    exclude_contracts:
        - SafeMath