# automatically fetch contract sources from Etherscan
autofetch_sources: true
dev_deployment_artifacts: true

compiler:
    solc:
        optimizer:
            enabled: true
            runs: 1000000